name: Build and Deploy Hugo Site with Nix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install Nix
      run: |
        curl -L https://nixos.org/nix/install | sh
        source /home/runner/.nix-profile/etc/profile.d/nix.sh
        mkdir -p /home/runner/.config/nix/
        echo "experimental-features = nix-command flakes" >> /home/runner/.config/nix/nix.conf

    - name: Build Hugo Site
      run: |
        source /home/runner/.nix-profile/etc/profile.d/nix.sh
        nix develop --extra-experimental-features nix-command --command website
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Ensure result directory exists and set permissions
      run: |
        mkdir -p result/
        chmod -R 777 result/

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: result/
        server-dir: ./
        protocol: ftp
        exclude:  |
          **/kaffeepause/**
          **/whitepaper/**
          **/scss/main.css
          **/scss/main.css.map